package edu.wpi.first.wpilibj.robottesting;

import java.util.Enumeration;
import java.util.Vector;

/**
 * Message hub for {@link AssertionFailure} messages generated by tests.
 * 
 * @author pmalmsten
 */
public class ProblemManager implements ProblemHandler {
    private Vector m_handlers = new Vector();
    private static ProblemManager s_instance;

    /**
     * Add the given handler such that it receives AssertionFailure messages
     * sent to this ProblemManager.
     *
     * @param handler The hander object to register for AssertionFailures.
     */
    public void addHandler(ProblemHandler handler) {
        if(handler == null)
            return;

        m_handlers.addElement(handler);
    }

    /**
     * Removes the given handler such that it no longer receives AssertionFailure
     * messages sent to this ProblemManager.
     *
     * @param handler The handler object to unregister from receiving
     *  AssertionFailures.
     */
    public void removeHandler(ProblemHandler handler) {
        if(handler == null)
            return;

        m_handlers.removeElement(handler);
    }

    /**
     * Informs this ProblemManager of an AssertionFailure which should be
     * relayed to each of its children.
     *
     * @param af The AssertionFailure to relay.
     */
    public void handleProblem(AssertionFailure af) {
        Enumeration handlers = m_handlers.elements();
        while(handlers.hasMoreElements()) {
            ProblemHandler ph = (ProblemHandler) handlers.nextElement();
            ph.handleProblem(af);
        }
    }

    /**
     * Gets a singleton instance of ProblemManager, used by default for handing
     * AssertionFailures generated by Assertion objects.
     *
     * @return The singleton ProblemManager instance.
     */
    public static ProblemManager getInstance() {
        if(s_instance == null)
            s_instance = new ProblemManager();
        return s_instance;
    }
}
